apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: erpnext-production
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        args:
          - "--character-set-server=utf8mb4"
          - "--collation-server=utf8mb4_unicode_ci"
          - "--skip-character-set-client-handshake"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "changeme123"
        - name: MYSQL_DATABASE
          value: "erpnext"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: erpnext-production
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
