apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erpnext-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AyoubDahir/argocd.git
    targetRevision: HEAD
    path: erpnext-gitops/environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: erpnext-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
